### PR TITLE
Updated font file

### PR DESCRIPTION
**Pull request by lyerelian**
Updated fonts and added a operative, armament, generator, and crew icons.  Also increased sized of the melee icon.

Also addressed comment #1 from the original file

### CODE REVIEW

**Comment by Owen-A** [comment]
lyerelian - I am basically inactive on this font now as i stopped with Legion. Do you want rights on the project?

**Comment by lyerelian** [comment]
Sure!  Github is new to me but one of the other commenters, stevegood, is
part of my local community and helping me with the organization so your
work will be in good hands.

Thanks,
Lance

**Comment by Owen-A** [comment]
I added you as a collaborator, i think that gives you enough privileges.

**Comment by lyerelian** [comment]
Awesome!  Thanks Owen

-Lance

**Pull request merged**
